<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="urn:oracle:b2b/damco/a2a/fact/payment"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="urn:oracle:b2b/damco/customer/partner1/payments"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns1="http://oracle.com/sca/soapservice/BDL.A2A.FACT/BDL.A2A.FACT/IN_Direct_FACT_UploadPayment"
                xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:inp2="http://xmlns.oracle.com/singleString">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/IN_Direct_FACT_UploadPaymentWrapper.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Message-PAYMENT"
                                       namespace="urn:oracle:b2b/damco/customer/partner1/payments"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="http://localhost:7003/soa-infra/directWsdl/default/BDL.A2A.FACT/IN_Direct_FACT_UploadPayment?resource=%2FWSDLs%2FIN_Direct_FACT_UploadPayment.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Message-PAYMENT" namespace="urn:oracle:b2b/damco/a2a/fact/payment"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED APR 05 13:32:18 CEST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:Message-PAYMENT>
      <tns:GroupRecord-01>
        <tns:Record-20>
          <xsl:choose>
            <xsl:when test="string-length (/ns0:Message-PAYMENT/ns0:Record-10/ns0:Field-OperationType ) > 4">
              <tns:Field-Type>
                <xsl:value-of select="substring (/ns0:Message-PAYMENT/ns0:Record-10/ns0:Field-OperationType, 1, 4 )"/>
              </tns:Field-Type>
            </xsl:when>
            <xsl:otherwise>
              <tns:Field-Type>
                <xsl:value-of select="/ns0:Message-PAYMENT/ns0:Record-10/ns0:Field-OperationType"/>
              </tns:Field-Type>
            </xsl:otherwise>
          </xsl:choose>
          <tns:Field-Date>
            <xsl:value-of select="/ns0:Message-PAYMENT/ns0:Record-10/ns0:Field-Date"/>
          </tns:Field-Date>
          <tns:Field-Time>
            <xsl:value-of select="/ns0:Message-PAYMENT/ns0:Record-10/ns0:Field-Time"/>
          </tns:Field-Time>
          <tns:Field-Amount>
            <xsl:value-of select="/ns0:Message-PAYMENT/ns0:Record-10/ns0:Field-Amount"/>
          </tns:Field-Amount>
          <tns:Field-Currency>
            <xsl:value-of select="xp20:upper-case (/ns0:Message-PAYMENT/ns0:Record-10/ns0:Field-Currency )"/>
          </tns:Field-Currency>
        </tns:Record-20>
      </tns:GroupRecord-01>
    </tns:Message-PAYMENT>
  </xsl:template>
</xsl:stylesheet>
